#!/bin/sh
set -e

. /usr/share/debconf/confmodule
db_version 2.0

action="$1"

umask 022


# The path to /usr/sbin/sshd is intentionally *not* prefixed by $DPKG_ROOT
# because when dpkg is called with --force-script-chrootless then this is in
# situations where we cannot execute binaries of the system which dpkg is
# told to install packages in and thus it cannot do a chroot() call. Instead,
# we use tools installed outside of the chroot and tell those tools to
# operate on the chroot at the location given by $DPKG_ROOT.
get_config_option() {
	option="$1"
	sshd_path=/usr/sbin/sshd

	[ -f "$DPKG_ROOT/etc/ssh/sshd_config" ] || return

	# begin-remove-after: released:forky
	if [ -e /usr/sbin/sshd.session-split ]; then
		sshd_path=/usr/sbin/sshd.session-split
	fi
	# end-remove-after
	"$sshd_path" -f "$DPKG_ROOT/etc/ssh/sshd_config" -G | sed -n "s/^$option //Ip"
}


create_key() {
	msg="$1"
	shift
	hostkeys="$1"
	shift
	file="$1"
	shift

	if echo "$hostkeys" | grep -x "$file" >/dev/null && \
	   [ ! -f "$DPKG_ROOT$file" ] ; then
		printf %s "$msg"
		ssh-keygen -q -f "$DPKG_ROOT$file" -N '' "$@"
		echo
		if command -v restorecon >/dev/null 2>&1; then
			restorecon "$DPKG_ROOT$file" "$DPKG_ROOT$file.pub"
		fi
		ssh-keygen -l -f "$DPKG_ROOT$file.pub"
	fi
}


create_keys() {
	hostkeys="$(get_config_option HostKey)"

	create_key "Creating SSH2 RSA key; this may take some time ..." \
		"$hostkeys" /etc/ssh/ssh_host_rsa_key -t rsa
	create_key "Creating SSH2 ECDSA key; this may take some time ..." \
		"$hostkeys" /etc/ssh/ssh_host_ecdsa_key -t ecdsa
	create_key "Creating SSH2 ED25519 key; this may take some time ..." \
		"$hostkeys" /etc/ssh/ssh_host_ed25519_key -t ed25519
}


new_config=

cleanup() {
	if [ "$new_config" ]; then
		rm -f "$new_config"
	fi
}


create_sshdconfig() {
	# XXX cjwatson 2016-12-24: This debconf template is very confusingly
	# named; its description is "Disable SSH password authentication for
	# root?", so true -> prohibit-password (the upstream default),
	# false -> yes.
	db_get openssh-server/permit-root-login
	permit_root_login="$RET"
	db_get openssh-server/password-authentication
	password_authentication="$RET"

	trap cleanup EXIT
	new_config="$(mktemp)"
	cp -aZ "$DPKG_ROOT/usr/share/openssh/sshd_config" "$new_config"
	if [ "$permit_root_login" != true ]; then
		sed -i 's/^#*PermitRootLogin .*/PermitRootLogin yes/' \
			"$new_config"
	fi
	if [ "$password_authentication" != true ]; then
		sed -i 's/^#PasswordAuthentication .*/PasswordAuthentication no/' \
			"$new_config"
	fi
	mkdir -pZ "$DPKG_ROOT/etc/ssh"
	ucf --three-way --debconf-ok \
		--sum-file "$DPKG_ROOT/usr/share/openssh/sshd_config.md5sum" \
		"$new_config" /etc/ssh/sshd_config
	ucfr openssh-server /etc/ssh/sshd_config
}

if [ "$action" = configure ]; then
	create_sshdconfig
	create_keys
	# begin-remove-after: released:forky
	if [ -e "$DPKG_ROOT/usr/sbin/sshd.session-split" ]; then
		# We're ready to restart the listener process so that it
		# executes sshd-session rather than sshd for new
		# connections, so we can remove this diversion now.  This
		# starts a brief window where new connections will fail
		# (ending when the service is restarted), but at least it's
		# all contained within this postinst.
		#
		# See openssh-server.preinst for why we use this odd package
		# name.
		echo "Finishing upgrade from pre-9.8 monolithic sshd ..."
		dpkg-divert --package openssh-client --remove --no-rename \
			--divert /usr/sbin/sshd.session-split /usr/sbin/sshd
		mv -f "$DPKG_ROOT/usr/sbin/sshd.session-split" "$DPKG_ROOT/usr/sbin/sshd"
	fi
	# end-remove-after
fi

#DEBHELPER#

db_stop

exit 0
